require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'searchpicture_front' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )
  



  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'searchpicture_frontTests' do
    inherit! :complete
  end
  
  use_flipper!({ 'Flipper-Folly' => '2.5.0' }) # update this part
     post_install do |installer|
     installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
     end
   end
   flipper_post_install(installer)
  end
end
